/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    HomeView: typeof import('./components/HomeView.vue')['default']
    HorizontalScroll: typeof import('./components/HorizontalScroll.vue')['default']
    MainCarrousel: typeof import('./components/carrousel/MainCarrousel.vue')['default']
    ProductsCarrousel: typeof import('./components/carrousel/ProductsCarrousel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
